Revert "ci: Drop git fetch"
This reverts commit 16f567278a7e48e3e647645d931d8227d4ba9894.

This reverts commit 20b74f6e4807f66384c097c432c712277a40a889.

We need this still while running the auto_updater job, otherwise the checked out repo returns an outdated list of remote branches preventing skipping when branch exists.

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/8827624977/viewer#L7422

```
Failed to push branch update/components_shaderc.bst-diff_md5-afa44b9-for-master to remote: Cmd('git') failed due to: exit code(1)
  cmdline: git push --set-upstream origin update/components_shaderc.bst-diff_md5-afa44b9-for-master
  stderr: 'To https://gitlab.com/freedesktop-sdk/freedesktop-sdk.git
 ! [rejected]        update/components_shaderc.bst-diff_md5-afa44b9-for-master -> update/components_shaderc.bst-diff_md5-afa44b9-for-master (fetch first)
error: failed to push some refs to 'https://gitlab.com/freedesktop-sdk/freedesktop-sdk.git'
```

was supposed to skipped if the remote branch was found

https://gitlab.com/BuildStream/infrastructure/gitlab-merge-request-generator/-/blob/661579cd3e35651413016b796e54779e92478b13/src/repo.py#L222-223 (cherry picked from commit 97d34c76e3d2c4c91c71bf818f908d0526ebf7c9)