perf: Force -Wno-error through patch and local_flags
The patch is still needed as it in places passes -Werror unconditionally
and ignores cflags.

This causes spurious errors like https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/10259142624
due to race condition during CI load.

```
          gcc -Wp,-MD,/buildstream-build/tools/perf/libbpf/staticobjs/.libbpf.o.d -Wp,-MT,/buildstream-build/tools/perf/libbpf/staticobjs/libbpf.o -fPIC -std=gnu89 -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wno-type-limits -Wstrict-aliasing=3 -Wshadow -Wno-switch-enum -Werror -Wall -I/buildstream-build/tools/perf/libbpf/ -I/buildstream-build/tools/include -I/buildstream-build/tools/include/uapi -I/buildstream-build/tools/arch/x86/include -fvisibility=hidden -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D"BUILD_STR(s)=#s" -c -o /buildstream-build/tools/perf/libbpf/staticobjs/libbpf.o libbpf.c
        threadmap.c:98:7: error: no previous prototype for 'perf_thread_map__pid' [-Werror=missing-prototypes]
           98 | pid_t perf_thread_map__pid(struct perf_thread_map *map, int idx)
              |       ^~~~~~~~~~~~~~~~~~~~
        cc1: all warnings being treated as errors
        make[4]: *** [/buildstream-build/tools/build/Makefile.build:86: /buildstream-build/tools/perf/libperf/threadmap.o] Error 1
        make[4]: *** Waiting for unfinished jobs....
        \
```