u-boot-unmatched: Add dependency on gnutls
```
      cc -Wp,-MD,tools/.mkeficapsule.o.d -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer   -std=gnu11   -DCONFIG_FIT_SIGNATURE -DCONFIG_FIT_SIGNATURE_MAX_SIZE=0xffffffff -DCONFIG_FIT_CIPHER -include ./include/compiler.h -idirafterinclude -idirafter./arch/riscv/include -idirafter./dts/upstream/include -I./scripts/dtc/libfdt -I./tools -DUSE_HOSTCC -D__KERNEL_STRICT_NAMES -D_GNU_SOURCE  -c -o tools/mkeficapsule.o tools/mkeficapsule.c
    tools/mkeficapsule.c:20:10: fatal error: gnutls/gnutls.h: No such file or directory
       20 | #include <gnutls/gnutls.h>
          |          ^~~~~~~~~~~~~~~~~
    compilation terminated.
```

(cherry picked from commit a739c2378469e2dc6a18f6decf26a4de5d1ccffd)