Include mount command in the toolbox image
Podman Toolbox requires mount command in the image. See:
https://github.com/containers/toolbox/blob/0.0.99.4/src/cmd/initContainer.go#L518

A toolbox container built from image freedesktopsdk/toolbox:23.08-beta-x86_64
will fail to start. Error message:

   Error: failed to bind /etc/machine-id to /run/host/etc/machine-id